### ISSUE TITLE
It takes long for the summary to be created

### ISSUE THREAD

**Issue by hdatteln** [dmmiller612/bert-extractive-summarizer#16]
Hi, 
When trying the out-of-the-box summarizer on an article with about 7000 words, it takes over 4 minutes to get a summary;
(I am running the example on my mac, no gpu)
Just want to check if that's that normal?

Thanks,
Heidi

**Comment by dmmiller612** [comment]
It could be a few things. When you first use the worker, a download is issued for the pretrained model. Depending on network speed, that can take a few minutes.  Good news is that once it is downloaded, it should be cached in your system.

The next thing could be the model you select. Distill Bert runs much faster than Bert-uncased large, due to the fewer parameters.

GPU is obviously preferable with the size of these models, but can be costly.

**Comment by hdatteln** [comment]
Thank you, Derek.
The download is not the issue here (happens on every run, not only the first);
I will look into using Distill Bert, and see how it goes
